# models/esm2_loader.py
# Auto-generated by 4_integrate.py — fine-tuned ESM2-650M binding predictor
import torch
import torch.nn as nn
from pathlib import Path
from transformers import EsmModel, EsmTokenizer

CKPT_PATH = Path(__file__).parent / "esm2_alchemy_best.pt"
MODEL_NAME = "facebook/esm2_t33_650M_UR50D"
MAX_SEQ_LEN = 512
EMBEDDING_DIM = 1280

_model = None
_tokenizer = None
_device = None


class ESM2BindingPredictor(nn.Module):
    def __init__(self, esm_model):
        super().__init__()
        self.esm = esm_model
        hidden = esm_model.config.hidden_size
        self.dropout = nn.Dropout(0.1)
        self.norm = nn.LayerNorm(hidden)
        self.regressor = nn.Sequential(
            nn.Linear(hidden, 512), nn.GELU(), nn.Dropout(0.1), nn.Linear(512, 1),
        )
        self.classifier = nn.Sequential(
            nn.Linear(hidden, 256), nn.GELU(), nn.Dropout(0.1), nn.Linear(256, 1),
        )

    def forward(self, input_ids, attention_mask):
        out = self.esm(input_ids=input_ids, attention_mask=attention_mask)
        mask = attention_mask.unsqueeze(-1).float()
        pooled = (out.last_hidden_state * mask).sum(1) / mask.sum(1)
        pooled = self.norm(self.dropout(pooled))
        return self.regressor(pooled).squeeze(-1), self.classifier(pooled).squeeze(-1)

    def embed(self, input_ids, attention_mask):
        """Return mean-pooled embedding (used by get_embedding())."""
        out = self.esm(input_ids=input_ids, attention_mask=attention_mask)
        mask = attention_mask.unsqueeze(-1).float()
        return (out.last_hidden_state * mask).sum(1) / mask.sum(1)


def load_esm2():
    global _model, _tokenizer, _device
    _device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    _tokenizer = EsmTokenizer.from_pretrained(MODEL_NAME)
    esm_base = EsmModel.from_pretrained(MODEL_NAME)
    _model = ESM2BindingPredictor(esm_base)

    if CKPT_PATH.exists():
        ckpt = torch.load(CKPT_PATH, map_location=_device, weights_only=False)
        _model.load_state_dict(ckpt["model_state"])
        print(
            f"Loaded fine-tuned ESM2 (val_loss={ckpt['val_loss']:.4f}, "
            f"val_acc={ckpt['val_accuracy']:.3f})"
        )
    else:
        print("WARNING: fine-tuned checkpoint not found, using base ESM2 weights")

    _model.to(_device).eval()
    return _model, _tokenizer


def get_embedding(sequence: str, model=None, alphabet=None) -> list:
    """Same signature as fair-esm loader; ``alphabet`` is the HF tokenizer."""
    global _model, _tokenizer, _device
    if _model is None:
        load_esm2()
    tok = _tokenizer(
        sequence[:MAX_SEQ_LEN],
        return_tensors="pt",
        truncation=True,
        padding=True,
    )
    with torch.no_grad():
        emb = _model.embed(
            tok["input_ids"].to(_device),
            tok["attention_mask"].to(_device),
        )
    return emb.squeeze(0).cpu().tolist()


def predict_binding(smiles: str, sequence: str) -> dict:
    """
    Predict binding-related outputs for a protein sequence (sequence-only model).
    ``smiles`` is accepted for API symmetry; binding heads were trained on sequence + pKi labels only.
    """
    del smiles  # reserved for future ligand-aware heads
    global _model, _tokenizer, _device
    if _model is None:
        load_esm2()
    tok = _tokenizer(
        sequence[:MAX_SEQ_LEN],
        return_tensors="pt",
        truncation=True,
        padding=True,
    )
    with torch.no_grad():
        pki_pred, logit = _model(
            tok["input_ids"].to(_device),
            tok["attention_mask"].to(_device),
        )
    pki = float(pki_pred.item())
    confidence = float(torch.sigmoid(logit).item())
    return {
        "pki": round(pki, 3),
        "active": confidence >= 0.5,
        "confidence": round(confidence, 3),
        "ki_nm": round(10 ** (9 - pki), 1),
    }
